
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls:
  - hosts:
    - rabbitmq.example.com ##change to url that you want to publish the rabbitmq
    secretName: rabbitmq-tls
  rules:
  - host: "rabbitmq.example.com" ##change to url that you want to publish the rabbitmq must same like above
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672