apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-reader-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "services", "events", "namespaces", "nodes", "limitranges", "persistentvolumes", "persistentvolumeclaims", "resourcequotas"]
  verbs: ["get", "watch", "list"]
