controller:
  config:
    enable-underscores-in-headers: "true"
    proxy-body-size: 128m
    proxy-connect-timeout: "3600"
    proxy-read-timeout: "3600"
    proxy-request-buffering: "off"
    proxy-send-timeout: "3600"
    send-timeout: "3600"
    use-forwarded-headers: "true"
  ingressClassResource:
    default: false
    name: nginx
  service:
    externalTrafficPolicy: Local
tcp:
  30010: default/postgress-postgresql:5432

## the format above is
## (port you want to publish to outside): (namespace of the service)/(name of the service):(port of the service)
